language: node_js
node_js: "10"
os: osx
osx_image: xcode10.2
script:
  - npm run lint
  - npm test
  - npm run electron-pack
branches:
  only:
    - master
    - develop
deploy:
  provider: releases
  api_key:
    secure: ERpJxGce5QXVN1V2uwVc+hlrPxBZwYhVq5XX1HI2e5d4SCUV/Mx3x2+ba9TdTQNvv9h6pjWScEjGVLvk/X6KXVIKlABNBB3zn3/lwJwAGUTD97IWCmyvYtcbNElTog/XXeg4j9/NwEDaL3jOOv1b8cVSCfzhi+znd48Dv73NKe74uaGPiN1WcD+hHMlh1lXorWH9MwJujNT5ske00xHi9PZHaYFHZpEAtM85cbq1JLpxLc9J7uqQyOLMQDfDDp4ZyiWsWT3f/1NwY3Yz2BrOvrAOo7i5u/7htRHckWXzcDxwpPyMPTZAsVjFzhbCLAmAyaHUo6VP7SwQvqNiU8PYS8lljN+XikwxY4FJWGMFUUYku6S0Fq0fzoxEEFQgLYNlstv9sKT0cxuT7/0y85ld6bskQRvhcowlVJ2z8aOgZHiBc365QaXSg2fmSb3cBnLgMSG68ADHKfoMRVs/NqOSgIzpqon2P6XgrD5QJlg70YM6T5FEAP3bJ7IKpqXorqZEUTyRpEUfX9G3xF2PGn/ERvsePsvmVw+Zd/XCU0TWjwUA1Yd5MWiCpKLYOjmh3hGs1rbHoRLqqrk6KNQ3KH6W8YLnHY+zGzmRh1Ri8IJR20sYPkaJQJPQMOdee4LtKt6ZaWIiTlQPVnt+IwRgpzQlia7ODAizcqnmgEhddyNRvcQ=
  file:
    - 'dist/loglady 1.0.0.AppImage'
    - 'dist/loglady-1.0.0.dmg'
    - 'dist/loglady Setup 1.0.0.exe'
  skip_cleanup: true
  on:
    branch: master
    tags: false
