language: node_js
node_js: "10"
os: osx
osx_image: xcode10.2
script:
  - npm run lint
  - npm test
  - npm run electron-pack
branches:
  only:
    - master
    - develop
deploy:
  provider: releases
  api_key:
    secure: Z9UcoMM9at0CwiOgpOXlv5XRdkzw5eZTNjsAa8f1rLogjHZ1Ns/HNlpo7/tqW75DTBRs78T7AsBRfXKNmXs6OocZZqpSGs/F2DOw3xg27aSdyDFcnNeX5XjENT7oibWD6O9UYLMKWpx76xMNUDTvAaf12/PphdQANQWT6ZrJR4hJ6uOIpHcNesjFyahKM66CtO8DpPIQy5GpV1btDniN2Tk/Mndi3tDnDMmodsKRanFjbPKahQfIvBwKCYo6sCQZJN4jtt4nopc7JriYXe3P2b77Kn0znih/OVhsCnqluepKYioG1hseeaknwM/mOatUFMIOHUUu6g3rfPN79axt31Mv4MpeiNV4T7lFSOmIDZZ1xzs9x41LmMa8umjQ+Xksah/4DjChEkrFGH1xhnKPz0zpQudy0dzt7P6T+AtvNw/kUI5B5jFNf8GKsvNYyL+9n1sYkeQpKO8ti0yJ31oCGkpo7M/Isujk5TImdV185FUYiK1k5r4ldglNwplozWFNtOJ/gwJ0OhMs/ok9xd0cnSdoOH1xACHyoS2LZypqWN6vFBf9rqCUxkwENzSLsfatOFDr1ULZu0/vkP8Yt7c1gP6b3jeXmGJLgnlSMu4TkkkE3KUFqCcOGPfb2/rFfcPSqq7VuCRbHz38T47rxU0dwxV4UWAA2V7mf+Gc0sysCpQ=
  file:
    - 'dist/loglady 1.0.0.AppImage'
    - 'dist/loglady-1.0.0.dmg'
    - 'dist/loglady Setup 1.0.0.exe'
  skip_cleanup: true
  on:
    branch: master
    tags: false
