language: node_js
node_js:
  - '8.11.4'
os: osx
install: npm install
script:
  - npm run lint
  - npm run test -- --coverage
  - npm run preelectron-pack
  - npm run electron-pack
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 'dist/loglady 1.0.0.AppImage'
  skip_cleanup: true
  on:
    tags: false
