language: node_js
node_js:
  - '8.11.4'
os: osx
script:
  - npm run lint
  - npm test
  - npm run electron-pack
branches:
  only:
    - master
    - develop
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 'dist/loglady 1.0.0.AppImage'
  skip_cleanup: true
  on:
    tags: false
