language: node_js
node_js:
  - 8.11.4
os: osx
script:
  - npm run lint
  - npm test
  - npm run electron-pack
branches:
  only:
    - master
    - develop
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file:
    - 'dist/loglady 1.0.0.AppImage'
    - 'dist/loglady-1.0.0.dmg'
    - 'dist/loglady Setup 1.0.0.exe'
  skip_cleanup: true
  on:
    branch: master
    tags: false
