language: node_js
node_js: '10'
os: osx
osx_image: xcode11.2
script:
  - npm run lint
  - npm test
  - npm run electron-pack
  - if [ "$TRAVIS_BRANCH" = "master"] && [ "$TRAVIS_PULL_REQUEST" = false ]; then npm run electron-deploy; fi
branches:
  only:
    - master
    - develop
