language: node_js
node_js:
  - 8.11.4
os: osx
script:
  - npm run lint
  - npm test
  - npm run electron-pack
branches:
  only:
    - master
    - develop
deploy:
  provider: releases
  api_key:
    secure: UA1RveBAQ4eF7SisUwS2sVMvdBVVvAUbP74I2odC34mU2sqRO9+qmOMYo+HL733vIbZWV9fPV27Yyz4mkXOU0pEoAHLxMzL2YHrlzrtnqwbrrl8Gpq0DLuaQMHphDlDPAdBlnLiZy8UyCEGq/F/8p706tCGrLnNMNfWssc0/hwvZ4CpwBpNZ8+72rObNqZ7u3qkZs0thWC8JzPkG7vpQBtZ74JdBfoAGKdJyLGoo0uDCwttO/sG5NlVcdrzVRshJkfl4QEMcdVanN991U0SGFZpPEFAXnfd0Sl4yjAUyQ0bmubv4cKp6MRv2PBvDyy8HgzQpqE3Ul2Cy3X4kxj7vt29PZ8wdu+3466Yi4kq9174nO8J/y28U85XCX9kRGGGehEH0focyzgnOJBhU6Zwxbt5/UiZa/0hn6LT5XVTKuZEVIoM6rEt2cccjmBTyJGN2szSV8aumuqaMu206IHZTAE7rFyCNAuAjK2EenFLl10giV+4M92FbCyumyvB68ts/X/bnnM5JFbnmGJEfdaNr1jpUtB1vSlLx5jiFvmqUX5YNb/K6pNEimChgY/3vaPjacu6nGpQhdyrVe2swgqYi8TT/+tPzgjvYk4nn0TfDznNGVW+75XD4XtDqPbp3Ytbe4UazJo3dn+C2q4N4t1Rc3HlaF8NqXl3f8WW2s7r4Y5E=
  file:
    - 'dist/loglady 1.0.0.AppImage'
    - 'dist/loglady-1.0.0.dmg'
    - 'dist/loglady Setup 1.0.0.exe'
  skip_cleanup: true
  on:
    branch: master
    tags: false
