name: I see you

on: [project_card]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: gustavjorlov/slacker@e74d5f0
        with:
          message: ${{github.actor}} ${{github.event.action}} card, ${{github.event.project_card.note}}
          slack-url: ${{secrets.SLACK_URL}}